doc.type.html
script
html
head 
utf8
viewport content=width=device-width, initial-scale=one>
title covid strings12 first round
filename=covid strings12 first round.js
first round =(highest overall seed, second highest seed, third highest seed, fourth highest seed,fifth highest seed,third low seed, second low seed,lowest overall seed)
highest overall seed = seed1
second highest seed=seed2
third highest seed=seed3
firstmiddleseed=seed4
second middle seed =seed5
third lowest seed= seed6
second lowest seed = seed7
lowest overall seed = seed8
addeventlistener(domcontentloaded, () => {
bracket = getelementbyid(bracket);
create matchup(pink versus orange)
create matchup(yellow versus red)
create matchup(purple versus blue)
create matchup(teal versus black)
matchup div=matchup
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.innerHTML =[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
round div=create element
round div class name=Covid Strings11 First Round
bracket.AppendChild(Round Div)
If (Event.Target.Covid Strings Seed List.Contains(Matchup))
Event.Target.Covid Strings Seed List.Toggle
Else:
AddMatchup
Import Java Util.Scanner
Import Java.Util
Questions[]Questions={
    Question1
    Question2
    Question3
    Question4
    Question5
    Question6
    Question7
    Question8
    Question9
    Question10
    Question11
    Question12
    Question13
    Question14
    Question15
    Question16
    If SelectedAnswer==Correct:
    return True
    If SelectedAnswer=InCorrect
    return False
    AdvancingTeam=Teams.Slice(Current Teams.Length)
     DeclareWinner
    Let Result= DeclareWinner(Team1 Score, Team2 Score)
    If Orange Score>=Forty:
    Console.Log(Orange RNA Messengers Win)
    Else:
    Consloe.Log(Pink Covid Disease Fighters Win)
    If Red Score>Forty:
    Console.Log(Red Protein Spikers Win)
    Else:
    Console.Log(Yellow Moxie Wins)
    If Blue Score>Forty:
    Console.Log(Blue Curve Crushers Win)
    Else:
    Console.Log(Purple Brave Hearts)
    If Black Score>Forty:
    Console.Log(Black Night Riders Win)
    Else:
    Console.Log(Teal Terminators Win)
    return Filename
