doc .type .html
script
filename=covid strings12.js    
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio(audio_file mp3)
audio.play 
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button (change color)
public fun with graphics(){
jpanel color panel=new j panel();
this add (panel,center )
jpanel button panel=
new j panel(flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener(){
override 
public actionperformed(actionevent e){
random r= newrandom();
colorpanel.setbackground(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen),)(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))(rnextint(thirteen)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener(){
override 
public actionperformed(actionevent e){
color m=jcolorchooser.showdialog(funwithgraphics.this,)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel, borderlayout.south)
public static void main(string [] args)
jframe f = new covid strings12()
f.set title(covid strings12)
f.set default closeoperation(jframe.exit_on_close);
F.SetSize
F.Set Visible(True);
<Label Id=LblScore>Zero</Label>
Var Score=Zero
If (Mult == X*Y)
[Non-Concatenated]
Score+=Ten
Else:
Score-=Ten
If (Mult == X*Y)
[Concatenated]
Score+=Twenty
Else:
Score-=Twenty
Var LblScore= Document.GetElementbyId(LblScore)
Lbl.Score.InnerHTML=Score
Public ActionPerformed(Action Event E) 
System.Out Print.In (Next Button Clicked)
Frame.Add(Next Button);
Frame Set Visible True
Const Object {A:One, B:Two, C:Three, D:Four, E:Five, F:Six, G:Seven, H:Eight}
Const Keys Object Keys(Team)
Const Entries Object Entries(Obj);
Const Object [Team Color]
CovidstringsTeamList12= [Red,Black,Blue, Orange, Pink, Purple, Teal, Yellow]
Covid Strings Phrase List12=[The Kids As Cardboard Cutouts Hides The Sad Reality Of Covids Impact On Kids
Internet Access Has Played A Crucial Role In Determining The Haves And Have Nots Of The Pandemic
Internet Access Has Determined In A Way Who Lives And Dies
This Is Why Internet Access Should Be A Basic Human Right
Even If You Dont Work From Home The Internet Likely Has Had An Impact On Your Life
The Internet Can Even Help You Get Important Information About Covid
HMPV Can Easily Show How Covid Is Not The Only Risk 
The Other Concern Is That The Decline In American Lifespans Will Continue Well Past Covid
Concatenated Strings
This+Could+Be+Part+Of+Demogprahic+Trends+That+Suggest+The+US+Population+Will+Decline+By+TWENTY SIXTY
If+So+The+Sheer+Amount+Of+Death+Could+Create+A+Crisis
Immigration+Could+Be+A+Potential+Solution
Nevertheless+Covid+Played+A+Role+In+Population+Decline
Specifically+The+Aftermath+States+It+Was+Accelerated+A+Decade
The+Idea+Of+A+Covid+Baby+Boom+Is+A+Little+More+Complicated
It+Started+Promising+But+It+Eventually+Receded
More+Flexibility+Can+Easily+Result+In+Some+Sort+Of+Baby+Bump]
Covid Strings12 Math Problems List=[]
Covid Strings Sentence12=[Covid Will Cause The US Population To Decline For Years To Come,Life Spans Will Drop A Couple Of Years Because Of Covid,One Morale Of Covid Is If You Have Internet Access Youre Lucky]
String.Split   
Arrays.AsList(List<String>)
For (String Ss:Arr){
System.OutprintIn(Ss)
Java Util.Scanner
Java.Util
Questions[]Questions={
Collections.Shuffle(Arrays.Aslist(Questions)
Userin.Select Team
Import Meta.
Class MyClass
Constructor (Non-Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
Constmyclass=New.Myclass(Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
Import Syntax 
Substring(Start,End)
Userin.Multiple Choice
If SelectedAnswer==Correct Answer:
Return True
Else:
Return False
return Filename
