doc.type.html
script
html
head 
utf8
viewport content=width=device-width, initial-scale=one
title covid strings12 first round bracket
div id bracket class bracket div
script src bracket.js
link rel= stylesheet href=css
head
body
bracket-container{}
matchup
solid zero;
padding 
text align center 
filename=covid strings12 first round.js
first round =(highest overall seed, second highest seed, third highest seed, fourth highest seed,fifth highest seed,third low seed, second low seed,lowest overall seed)
highest overall seed = seed1
second highest seed=seed2
third highest seed=seed3
firstmiddleseed=seed4
second middle seed =seed5
third lowest seed= seed6
second lowest seed = seed7
lowest overall seed = seed8
addeventlistener(domcontentloaded, () => {
bracket = getelementbyid(bracket);
matchup1=(pink versus orange)
matchup2=(yellow versus red)
matchup3=(purple versus blue)
matchup4=(teal versus black)
matchup div=matchup
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.inner html =[matchup]
rounddiv.appendchild(matchup)
for (i in covid strings first round)
round div=create element
round div class name=covid strings11 first round
bracket.appendchild(round div)
if (event.target.covid strings seed list.contains(matchup))
event.target.covid strings seed list.toggle
else:
addmatchup
java util.scanner
java.util
questions[]questions={
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
question15
question16
if selectedanswer==correct:
return true
if selectedanswer=incorrect
return false
advancingteam=slice(current teams)
declarewinner
result=declarewinner(matchup1)
if orange score>=forty:
console.log(orange rna messengers win)
else:
consloe.log(pink covid disease fighters win)
result=declarewinner(matchup2)
if red score>=forty:
console.log(red protein spikers win)
else:
console.log(yellow moxie wins)
result=declarewinner(matchup3)
if blue score>=forty:
console.log(blue curve crushers win)
else:
console.log(purple brave hearts)
result=declarewinner(matchup4)
if black score>=forty:
console.log(black night riders win)
else:
console.log(teal terminators win)
return filename
